// Generated by CoffeeScript 1.10.0
(function() {
  var h, meta, tape;

  h = require('hyperscript');

  tape = require('tape');

  meta = require('../')(h);

  tape('meta author tag', function(t) {
    var actual_output, desired_output;
    t.plan(1);
    desired_output = '<meta content="My name" name="author"></meta>';
    actual_output = meta.author('My name').outerHTML;
    return t.deepEqual(actual_output, desired_output);
  });

}).call(this);
