// Generated by CoffeeScript 1.10.0
(function() {
  var h, meta, tape;

  h = require('hyperscript');

  tape = require('tape');

  meta = require('../')(h);

  tape('script tag', function(t) {
    var actual_output, desired_output, func;
    t.plan(1);
    desired_output = '<script type="text/javascript">(function () {})()</script>';
    func = function() {};
    actual_output = meta.script(func).outerHTML;
    return t.deepEqual(actual_output, desired_output);
  });

}).call(this);
