// Generated by CoffeeScript 1.10.0
(function() {
  var h, meta, tape;

  h = require('hyperscript');

  tape = require('tape');

  meta = require('../')(h);

  tape('meta viewport tag', function(t) {
    var actual_output, desired_output;
    t.plan(1);
    desired_output = '<meta content="width=device-width, initial-scale=1" name="viewport"></meta>';
    actual_output = meta.viewport().outerHTML;
    return t.deepEqual(actual_output, desired_output);
  });

}).call(this);
