// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(h) {
    return function(content) {
      return h('meta', {
        content: content,
        name: 'author'
      });
    };
  };

}).call(this);
