// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(h) {
    return function(content) {
      if (content == null) {
        content = 'utf-8';
      }
      return h('meta', {
        charset: content
      });
    };
  };

}).call(this);
