// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(h) {
    return function(content, http_equiv) {
      if (content == null) {
        content = 'IE=edge';
      }
      if (http_equiv == null) {
        http_equiv = 'X-UA-Compatible';
      }
      return h('meta', {
        content: content,
        'http-equiv': http_equiv
      });
    };
  };

}).call(this);
