// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(h) {
    return {
      author: require('./author')(h),
      charset: require('./charset')(h),
      description: require('./description')(h),
      http_equiv: require('./http_equiv')(h),
      script: require('./script')(h),
      viewport: require('./viewport')(h)
    };
  };

}).call(this);
