// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(h) {
    return function(func) {
      return h('script', {
        type: 'text/javascript'
      }, "(" + (func.toString()) + ")()");
    };
  };

}).call(this);
