// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(h) {
    return function(content) {
      if (content == null) {
        content = "width=device-width, initial-scale=1";
      }
      return h('meta', {
        content: content,
        name: 'viewport'
      });
    };
  };

}).call(this);
